name       : egl-wayland
version    : 1.1.7
release    : 10
source     :
    - https://github.com/NVIDIA/egl-wayland/archive/refs/tags/1.1.7.tar.gz : 2b4ed459e4b2c77c47f15ad9b32da1b2b855a84db8f832e176fdd1fd49b14d36
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
    - pkgconfig(x11)
patterns   :
    - devel : /usr/share/wayland-*/*.xml
rundeps    :
    - devel : eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
