name       : egl-wayland
version    : 1.0.2
release    : 1
source     :
    - git|https://github.com/NVIDIA/egl-wayland.git : f6ba0a52a7857a351758d328c4c86960abad80a1
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
patterns   :
    - devel: /usr/share/wayland-*/*.xml
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
