name       : egl-wayland
version    : 1.1.1
release    : 5
source     :
    - https://github.com/NVIDIA/egl-wayland/archive/1.1.1.tar.gz : d73a6344e766ca0cb0d3b3547173b1d7066f9dddc85e689f1b0b3fe466f54b51
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
patterns   :
    - devel : /usr/share/wayland-*/*.xml
rundeps    :
    - devel : eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
