name       : egl-wayland
version    : 1.1.4
release    : 7
source     :
    - https://github.com/NVIDIA/egl-wayland/archive/1.1.4.tar.gz : b3cfb99803a0324478f0824e35521a42ade118e7c11aa9a6829a2dc82ca2453c
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
    - pkgconfig(x11)
patterns   :
    - devel : /usr/share/wayland-*/*.xml
rundeps    :
    - devel : eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %patch -p1 < $pkgfiles/mesa.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
