name       : egl-wayland
version    : 1.1.5
release    : 9
source     :
    - https://github.com/NVIDIA/egl-wayland/archive/1.1.5.tar.gz : 61405575b09c6cfc7fa53658691742aa0872233305664441b1917caac92f4683
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
    - pkgconfig(x11)
patterns   :
    - devel : /usr/share/wayland-*/*.xml
rundeps    :
    - devel : eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
