name       : egl-wayland
version    : 1.0.3
release    : 2
source     :
    - git|https://github.com/NVIDIA/egl-wayland.git : b283689e369116aaf41ffac70d4eeef19ce133a4
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-scanner)
patterns   :
    - devel: /usr/share/wayland-*/*.xml
rundeps    :
    - devel: eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
