name       : egl-wayland
version    : 1.1.8
release    : 11
source     :
    - https://github.com/NVIDIA/egl-wayland/archive/refs/tags/1.1.8.tar.gz : 12bee9accf121987b0f0d6fb1a4e3b1fc5855b116c50d8d9e035edd02c82f88c
license    : MIT
component  : programming.library
summary    : The EGLStream-based Wayland external platform
description: |
    This library implements an EGL External Platform interface to work along with EGL drivers that support the external platform mechanism.
builddeps  :
    - pkgconfig(eglexternalplatform)
    - pkgconfig(gl)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(x11)
patterns   :
    - devel : /usr/share/wayland-*/*.xml
rundeps    :
    - devel : eglexternalplatform
optimize   :
    - no-symbolic  # We set symbolic-functions usually but they have -Bsymbolic.
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
